# Generated by Django 5.0.3 on 2026-07-01 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='secure_vault_repository/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_status', models.CharField(choices=[('QUEUED', 'Queued for Ingestion Processing Analysis'), ('PROCESSED', 'AI Parsing Diagnostics Pipelines Completed'), ('FAILED', 'Analysis Pipeline Breakdown Encountered')], default='QUEUED', max_length=20)),
                ('extracted_raw_ocr_data', models.TextField(blank=True, null=True)),
                ('generated_summary_abstract', models.TextField(blank=True, null=True)),
                ('extracted_meta_keywords', models.JSONField(blank=True, default=list)),
                ('detected_category_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='departments.department')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kv_document_vault_ledger',
            },
        ),
    ]
