# Generated by Django 5.0.3 on 2026-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
