# Generated by Django 5.0.3 on 2026-07-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('OPERATIONS', 'Operations & Mining'), ('ADMIN', 'Executive & Administration'), ('TECH', 'Technology & R&D'), ('SUPPORT', 'Support & Services'), ('HR', 'Human Resources'), ('FINANCE', 'Finance & Accounts'), ('SAFETY', 'Safety & Compliance')], default='OPERATIONS', max_length=50),
        ),
    ]
