# Generated by Django 5.0.3 on 2026-07-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='division_head_type',
            field=models.CharField(choices=[('GM', 'General Manager (GM)'), ('MANAGER', 'Department Manager'), ('DIRECTOR', 'Project Director'), ('CSO', 'Chief Safety Officer (CSO)'), ('SUPERINTENDENT', 'Superintendent'), ('LEAD', 'Operations Lead')], default='MANAGER', max_length=50),
        ),
    ]
